// apps/portfolio-next/src/components/HamburgerButton.vue
<script setup lang="ts">
const { isSidebarOpen, className } = defineProps<{
  className?: string;
  isSidebarOpen: boolean;
}>();
const emit = defineEmits<{
  (e: "click"): void;
}>();
</script>

<template>
  <button
    :class="[
      'flex-center the-white-button relative',
      'h-auto min-h-[3rem] w-12 border-r',
      className,
    ]"
    @click="emit('click')"
  >
    <img
      src="/assets/menu-burger.svg"
      alt="Menu"
      height="28px"
      width="28px"
      class="absolute-center transition-opacity"
      :class="{ 'opacity-0': isSidebarOpen, 'opacity-100': !isSidebarOpen }"
    />
    <img
      src="/assets/menu-close.svg"
      alt="Close"
      height="28px"
      width="28px"
      class="absolute-center transition-opacity"
      :class="{ 'opacity-0': !isSidebarOpen, 'opacity-100': isSidebarOpen }"
    />
  </button>
</template>

// apps/portfolio-next/src/components/HamburgerButton.svelte
<script lang="ts">
  export let isOpen: boolean;
</script>

<button class="flex-center relative h-auto min-h-[3rem] w-12 border-r" on:click>
  <img
    src="/assets/menu-burger.svg"
    alt="Menu"
    height="24px"
    width="24px"
    class="absolute-center transition-opacity"
    class:opacity-0={isOpen}
    class:opacity-100={!isOpen}
  />
  <img
    src="/assets/menu-close.svg"
    alt="Close"
    height="24px"
    width="24px"
    class="absolute-center transition-opacity"
    class:opacity-0={!isOpen}
    class:opacity-100={isOpen}
  />
</button>
