// apps/portfolio-next/src/components/Header.svelte
<script lang="ts">
  import { tweened } from "svelte/motion";
  import { cubicOut } from "svelte/easing";
  import { sections } from "@/data/sections";
  import HamburgerButton from "./HamburgerButton.svelte";

  let headerHeight = 50;
  let menuOpened = false;
  const menuX = tweened(-100, {
    duration: 200,
    easing: cubicOut,
  });
  const backdropOpacity = tweened(0, {
    duration: 300,
    easing: cubicOut,
  });
  const toggleMenu = () => {
    menuX.set(menuOpened ? -100 : 0, {
      delay: menuOpened ? 0 : 80,
    });
    backdropOpacity.set(menuOpened ? 0 : 0.5, {
      delay: menuOpened ? 80 : 0,
    });
    menuOpened = !menuOpened;
  };
</script>

<header class="sticky top-0 z-30 flex border-b-2 bg-white p-0">
  <HamburgerButton isOpen={menuOpened} on:click={toggleMenu} />
</header>

<button
  type="button"
  class="fixed inset-0 z-10 bg-black opacity-0"
  class:pointer-events-auto={menuOpened}
  class:pointer-events-none={!menuOpened}
  style:opacity={$backdropOpacity}
  on:click={toggleMenu}
/>

<div
  class="absolute z-40 w-screen border-r bg-white shadow md:max-w-xs"
  style:height={`calc(100vh - ${headerHeight}px)`}
  style:transform="translate3d({$menuX}%,0,0)"
  style:top={headerHeight + "px"}
>
  <nav class="contents">
    <ul class="flex flex-col text-xs">
      {#each sections as section (section.id)}
        <li class="contents">
          <a href={section.link} class="border-b px-8 py-3">
            {section.name}
          </a>
        </li>
      {/each}
    </ul>
  </nav>
</div>

// apps/portfolio-next/src/components/Header.vue
<script setup lang="ts">
import { ref } from "vue";
import { sections } from "~/data/sections";
import reverse from "lodash-es/reverse";
import anime from "animejs/lib/anime.es.js";
import HamburgerButton from "~/components/HamburgerButton.vue";
import ThemeSwithcerButton from "~/components/ThemeSwithcerButton.vue";
import Sidebar from "~/components/Sidebar.vue";

const sidebarOpened = ref(false);
const sidebarRef = ref<InstanceType<typeof Sidebar> | null>(null);

const changeMenuOpened = (isOpen?: boolean) => {
  if (!sidebarRef.value) return;

  isOpen ??= !sidebarOpened.value;
  let modalX = ["-100%", "0%"];
  let backdropOpacity = [0, 0.5];

  if (!isOpen) {
    modalX = reverse(modalX);
    backdropOpacity = reverse(backdropOpacity);
  }

  anime({
    targets: sidebarRef.value?.backdropRef,
    duration: 300,
    easing: "easeInOutQuad",
    opacity: backdropOpacity,
    translateZ: 0,
  });

  anime({
    targets: sidebarRef.value?.modalRef,
    duration: 200,
    easing: "easeInOutQuad",
    translateX: modalX,
    translateZ: 0,
  });

  sidebarOpened.value = isOpen;
};
</script>

<template>
  <header class="fixed top-0 z-30 w-full overflow-hidden border-b-2 bg-white p-0">
    <div class="mx-auto flex max-w-[90rem] items-center justify-between">
      <HamburgerButton
        class="md:hidden"
        :is-sidebar-open="sidebarOpened"
        @click="changeMenuOpened"
      />
      <div
        :class="[
          'font-racing-sans text-[1.75rem]',
          'max-md:absolute-center',
          'md:text-3xl',
          'md:px-4 md:py-2',
        ]"
      >
        nurliman.
      </div>
      <div class="hidden h-7 w-px bg-zinc-600 md:flex" />
      <nav class="hidden md:contents">
        <ul class="flex flex-1 flex-row px-3 text-xs uppercase">
          <li v-for="section in sections" :key="section.id" class="contents">
            <a
              :href="section.link"
              class="the-white-button rounded-full px-3 py-1.5"
              @click="changeMenuOpened(false)"
            >
              {{ section.name }}
            </a>
          </li>
        </ul>
      </nav>
      <ThemeSwithcerButton />
    </div>
  </header>

  <client-only>
    <Sidebar
      ref="sidebarRef"
      :is-open="sidebarOpened"
      :header-height="50"
      @change="({ isOpen }) => changeMenuOpened(isOpen)"
    />
  </client-only>
</template>
