// apps/portfolio-next/src/lib/components/Header.svelte
<script lang="ts">
  import { clsx } from "clsx";
  import { tweened } from "svelte/motion";
  import { cubicOut } from "svelte/easing";
  import { sections } from "$lib/data/sections";
  import HamburgerButton from "$lib/components/HamburgerButton.svelte";
  import ThemeSwithcerButton from "$lib/components/ThemeSwithcerButton.svelte";
  import Sidebar from "$lib/components/Sidebar.svelte";

  let sidebarOpened = false;
  const sidebarModalX = tweened(-100, {
    duration: 200,
    easing: cubicOut,
  });
  const sidebarBackdropOpacity = tweened(0, {
    duration: 300,
    easing: cubicOut,
  });
  const changeMenuOpened = (isOpen?: boolean) => {
    isOpen ??= !sidebarOpened;

    if (isOpen) {
      sidebarModalX.set(0);
      sidebarBackdropOpacity.set(0.5);
      sidebarOpened = true;
    } else {
      sidebarModalX.set(-100);
      sidebarBackdropOpacity.set(0);
      sidebarOpened = false;
    }
  };
</script>

<header class="fixed top-0 z-30 w-full overflow-hidden border-b-2 bg-white p-0">
  <div class="mx-auto flex max-w-[90rem] items-center justify-between">
    <HamburgerButton
      class="md:hidden"
      isSidebarOpen={sidebarOpened}
      on:click={() => changeMenuOpened()}
    />
    <div
      class={clsx(
        "font-racing-sans text-[1.75rem]",
        "max-md:absolute-center",
        "md:text-3xl",
        "md:px-4 md:py-2",
      )}
    >
      nurliman.
    </div>
    <div class="hidden h-7 w-px bg-zinc-600 md:flex" />
    <nav class="hidden md:contents">
      <ul class="flex flex-1 flex-row px-3 text-xs uppercase">
        {#each sections as section (section.id)}
          <li class="contents">
            <a
              href={section.link}
              class="the-white-button rounded-full px-3 py-1.5"
              on:click={() => changeMenuOpened(false)}
            >
              {section.name}
            </a>
          </li>
        {/each}
      </ul>
    </nav>
    <ThemeSwithcerButton />
  </div>
</header>

<Sidebar
  isOpen={sidebarOpened}
  backdropOpacity={$sidebarBackdropOpacity}
  modalX={$sidebarModalX}
  headerHeight={50}
  on:change={(e) => changeMenuOpened(e.detail.isOpen)}
/>

// apps/portfolio-next/src/components/Header.vue
<script setup lang="ts">
import { ref } from "vue";
import { sections } from "~/data/sections";
import reverse from "lodash-es/reverse";
import anime from "animejs/lib/anime.es.js";
import HamburgerButton from "~/components/HamburgerButton.vue";
import ThemeSwithcerButton from "~/components/ThemeSwithcerButton.vue";
import Sidebar from "~/components/Sidebar.vue";

const sidebarOpened = ref(false);
const sidebarRef = ref<InstanceType<typeof Sidebar> | null>(null);

const changeMenuOpened = (isOpen?: boolean) => {
  if (!sidebarRef.value) return;

  isOpen ??= !sidebarOpened.value;
  let modalX = ["-100%", "0%"];
  let backdropOpacity = [0, 0.5];

  if (!isOpen) {
    modalX = reverse(modalX);
    backdropOpacity = reverse(backdropOpacity);
  }

  anime({
    targets: sidebarRef.value?.backdropRef,
    duration: 300,
    easing: "easeInOutQuad",
    opacity: backdropOpacity,
    translateZ: 0,
  });

  anime({
    targets: sidebarRef.value?.modalRef,
    duration: 200,
    easing: "easeInOutQuad",
    translateX: modalX,
    translateZ: 0,
  });

  sidebarOpened.value = isOpen;
};
</script>

<template>
  <header class="fixed top-0 z-30 w-full overflow-hidden border-b-2 bg-white p-0">
    <div class="mx-auto flex max-w-[90rem] items-center justify-between">
      <HamburgerButton
        class="md:hidden"
        :is-sidebar-open="sidebarOpened"
        @click="changeMenuOpened"
      />
      <div
        :class="[
          'font-racing-sans text-[1.75rem]',
          'max-md:absolute-center',
          'md:text-3xl',
          'md:px-4 md:py-2',
        ]"
      >
        nurliman.
      </div>
      <div class="hidden h-7 w-px bg-zinc-600 md:flex" />
      <nav class="hidden md:contents">
        <ul class="flex flex-1 flex-row px-3 text-xs uppercase">
          <li v-for="section in sections" :key="section.id" class="contents">
            <a
              :href="section.link"
              class="the-white-button rounded-full px-3 py-1.5"
              @click="changeMenuOpened(false)"
            >
              {{ section.name }}
            </a>
          </li>
        </ul>
      </nav>
      <ThemeSwithcerButton />
    </div>
  </header>

  <client-only>
    <Sidebar
      ref="sidebarRef"
      :is-open="sidebarOpened"
      :header-height="50"
      @change="({ isOpen }) => changeMenuOpened(isOpen)"
    />
  </client-only>
</template>
