// apps/portfolio-next/src/lib/components/Sidebar.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import { sections } from "$lib/data/sections";
  import { socials } from "$lib/data/socials";

  const dispatch = createEventDispatcher<{
    change: { isOpen: boolean };
  }>();

  export let isOpen: boolean;
  export let backdropOpacity: number;
  export let headerHeight: number;
  export let modalX: number;
</script>

<button
  type="button"
  class="fixed inset-0 z-10 bg-black opacity-0 md:hidden"
  class:pointer-events-auto={isOpen}
  class:pointer-events-none={!isOpen}
  style:opacity={backdropOpacity}
  on:click={() => dispatch("change", { isOpen: !isOpen })}
/>

<div
  class="absolute z-40 flex w-screen flex-col border-r bg-white shadow sm:max-w-xs md:hidden"
  style:height={`calc(100vh - ${headerHeight}px)`}
  style:transform="translate3d({modalX}%,0,0)"
  style:top={headerHeight + "px"}
>
  <nav class="contents">
    <ul class="flex flex-col text-xs uppercase">
      {#each sections as section (section.id)}
        <li class="contents">
          <a
            href={section.link}
            class="the-white-button border-b px-8 py-3 hover:font-semibold"
            on:click={() => dispatch("change", { isOpen: false })}
          >
            {section.name}
          </a>
        </li>
      {/each}
    </ul>
  </nav>
  <div class="h-px w-px flex-1" />
  <div class="flex bg-white p-5 border-t">
    <ul class="flex flex-row space-x-3.5">
      {#each socials as social (social.link)}
        <li class="flex">
          <a href={social.link} target="_blank" class="p-1.5 hover:bg-zinc-200 border rounded">
            <img src={social.iconUrl} alt={social.name} class="h-[18px] w-[18px]" />
          </a>
        </li>
      {/each}
    </ul>
  </div>
</div>

// apps/portfolio-next/src/components/Sidebar.vue
<script setup lang="ts">
import { ref } from "vue";
import { sections } from "~/data/sections";
import { socials } from "~/data/socials";

const backdropRef = ref<HTMLElement | null>(null);
const modalRef = ref<HTMLElement | null>(null);

const { isOpen, headerHeight } = defineProps<{
  isOpen: boolean;
  headerHeight: number;
}>();

const emit = defineEmits<{
  (e: "change", payload: { isOpen: boolean }): void;
}>();

defineExpose({
  backdropRef,
  modalRef,
});
</script>

<template>
  <button
    ref="backdropRef"
    type="button"
    class="fixed inset-0 z-10 w-screen bg-black opacity-0 opacity-0 md:hidden"
    :class="{
      'pointer-events-auto': isOpen,
      'pointer-events-none': !isOpen,
    }"
    @click="emit('change', { isOpen: false })"
  />

  <div
    ref="modalRef"
    :class="[
      'fixed z-40 flex w-screen flex-col border-r bg-white sm:max-w-xs md:hidden',
      '-translate-x-full will-change-transform',
    ]"
    :style="{
      height: `calc(100vh - ${headerHeight}px)`,
      top: `${headerHeight}px`,
    }"
  >
    <nav class="contents">
      <ul class="flex flex-col text-xs uppercase">
        <li v-for="section in sections" :key="section.id" class="contents">
          <a
            :href="section.link"
            class="the-white-button border-b px-8 py-3 hover:font-semibold"
            @click="emit('change', { isOpen: false })"
          >
            {{ section.name }}
          </a>
        </li>
      </ul>
    </nav>
    <div class="h-px w-px flex-1" />
    <div class="flex border-t bg-white p-5">
      <ul class="flex flex-row space-x-3.5">
        <li v-for="social in socials" :key="social.link + social.name" class="flex">
          <a :href="social.link" target="_blank" class="rounded border p-1.5 hover:bg-zinc-200">
            <img :src="social.iconUrl" :alt="social.name" class="h-[18px] w-[18px]" />
          </a>
        </li>
      </ul>
    </div>
  </div>
</template>
