// apps/portfolio-next/src/components/TheButton.vue
<script setup lang="ts">
import type { ButtonHTMLAttributes, PropType } from "vue";
import type { VariantProps } from "cva";
import { cva } from "cva";

const buttonVariant = cva({
  base: "brutal-btn",
  variants: {
    color: {
      "white-pink": "brutal-btn-white-pink",
      white: "brutal-btn-white",
      zinc: "brutal-btn-zinc",
      teal: "brutal-btn-teal",
    },
    border: {
      sm: "brutal-btn-border-sm",
      true: "brutal-btn-border",
    },
    shadow: {
      sm: "brutal-shadow-sm activable",
      true: "brutal-shadow activable",
    },
  },
});

export type ButtonVariant = VariantProps<typeof buttonVariant>;

defineProps({
  color: String as PropType<ButtonVariant["color"]>,
  border: [Boolean, String] as PropType<ButtonVariant["border"]>,
  shadow: [Boolean, String] as PropType<ButtonVariant["shadow"]>,
  component: {
    default: "button" as any,
  },
  type: {
    type: String as PropType<ButtonHTMLAttributes["type"]>,
    default: "button",
  },
});
</script>

<template>
  <component
    :is="component"
    :type="['input', 'button'].includes(component) ? type : undefined"
    :class="buttonVariant({ border, color, shadow })"
  >
    <slot />
  </component>
</template>

// apps/portfolio-next/src/components/TheButton.tsx
import type { JSX, ValidComponent } from "solid-js";
import { mergeProps, splitProps } from "solid-js";
import { Dynamic, type DynamicProps } from "solid-js/web";
import { cva, cx, type VariantProps } from "cva";

const buttonVariant = cva({
  base: "brutal-btn",
  variants: {
    color: {
      "white-pink": "brutal-btn-white-pink",
      white: "brutal-btn-white",
      zinc: "brutal-btn-zinc",
      teal: "brutal-btn-teal",
    },
    border: {
      sm: "brutal-btn-border-sm",
      true: "brutal-btn-border",
    },
    shadow: {
      sm: "brutal-shadow-sm activable",
      true: "brutal-shadow activable",
    },
  },
});

export type ButtonVariant = VariantProps<typeof buttonVariant>;

export type TheButtonBaseProps = ButtonVariant &
  Pick<JSX.HTMLAttributes<any>, "children" | "class" | "classList">;

export type TheButtonProps<T extends ValidComponent> = TheButtonBaseProps &
  Omit<DynamicProps<T>, keyof TheButtonBaseProps | "component"> & { component?: T };

function TheButton(props: TheButtonProps<"button">): JSX.Element;
function TheButton<T extends ValidComponent>(props: TheButtonProps<T>): JSX.Element;
function TheButton<T extends ValidComponent = "button">(props: TheButtonProps<T>): JSX.Element {
  const propsWithDefaults = mergeProps(
    {
      component: "button",
    },
    props,
  );

  const [localProps, buttonVariantProps, restProps] = splitProps(
    propsWithDefaults,
    ["children", "component", "class", "classList"],
    ["color", "border", "shadow"],
  );

  return (
    <Dynamic
      component={localProps.component as "button" | NonNullable<T>}
      class={cx(buttonVariant(buttonVariantProps), localProps.class, localProps.classList)}
      {...restProps}
    >
      {localProps.children}
    </Dynamic>
  );
}

export default TheButton;
