// apps/portfolio/src/routes/resume/+page.svelte
<script lang="ts">
  import DownloadIcon from "@lucide/svelte/icons/download";
  import NeobrutalismBadge from "$lib/components/NeobrutalismBadge.svelte";
  import NeobrutalismButton from "$lib/components/NeobrutalismButton.svelte";
  import TableOfContents from "$lib/components/TableOfContents.svelte";
  import { HEADER_HEIGHT } from "$lib/constants";
  import { certificates } from "$lib/data/certificates";
  import { education } from "$lib/data/education";
  import { experiences } from "$lib/data/experiences";
  import { knowledge } from "$lib/data/knowledge";
  import { otherSkills, technicalSkills } from "$lib/data/skills";
  import { IsLarge } from "$lib/hooks/is-large.svelte";
  import Certificates from "./Certificates.svelte";
  import Skills from "./Skills.svelte";
  import Timeline from "./Timeline.svelte";
  import type { TimelineItem } from "./types";

  const PAGE_TITLE = "Resume & Experience | Nurliman Diara Aria - Full-Stack Developer";
  const PAGE_DESCRIPTION =
    "Comprehensive resume showcasing 4+ years of full-stack development experience, technical skills, and professional achievements. Download available.";
  const PAGE_KEYWORDS =
    "software engineer resume, full-stack developer CV, technical skills, professional experience, software development portfolio, developer resume download";
  const PAGE_IMAGE_ALT = "Resume & Experience - Nurliman Diara Aria";
  const PAGE_AUTHOR = "Nurliman Diara Aria";

  const experiencesTimeline: TimelineItem[] = experiences.map((exp) => ({
    period: exp.period,
    institution: exp.company,
    title: exp.title,
    description: exp.description,
  }));

  const educationsTimeline: TimelineItem[] = education.map((edu) => ({
    period: edu.period,
    institution: edu.school,
    title: edu.field,
    description: edu.description,
  }));

  const tocSections = [
    { id: "summary", title: "Summary" },
    { id: "experience", title: "Experience" },
    { id: "education", title: "Education" },
    { id: "technical-skills", title: "Technical Skills" },
    { id: "other-skills", title: "Other Skills" },
    { id: "knowledges", title: "Knowledges" },
    { id: "certifications", title: "Certifications" },
  ];

  const isLarge = new IsLarge();
</script>

<svelte:head>
  <title>{PAGE_TITLE}</title>
  <meta name="description" content={PAGE_DESCRIPTION} />
  <meta name="keywords" content={PAGE_KEYWORDS} />
  <meta property="og:title" content={PAGE_TITLE} />
  <meta property="og:description" content={PAGE_DESCRIPTION} />
  <meta property="og:type" content="profile" />
  <meta property="og:image:alt" content={PAGE_IMAGE_ALT} />
  <meta name="twitter:title" content={PAGE_TITLE} />
  <meta name="twitter:description" content={PAGE_DESCRIPTION} />
  <meta name="twitter:image:alt" content={PAGE_IMAGE_ALT} />
  <meta property="og:article:author" content={PAGE_AUTHOR} />
</svelte:head>

<main class="relative container flex w-full flex-col">
  <div class="mt-16 mb-24 flex w-full justify-between">
    <!-- Main Content -->
    <div class="mx-auto flex w-full max-w-xl flex-col lg:mx-0 lg:max-w-full lg:flex-1">
      <h1 class="font-transducer-extended text-3xl font-semibold md:text-4xl lg:text-5xl">
        Resume
      </h1>
      <div class="mb-5"></div>

      <!-- Updated CV Download Section -->
      <div
        class={[
          "mb-8 flex flex-col space-y-4",
          "md:flex-row md:items-center md:space-y-0 md:space-x-4",
        ]}
      >
        <p class="text-muted-foreground text-sm">
          Download my resume for a detailed summary of my experience.
        </p>
        <NeobrutalismButton
          variant="zinc"
          size="sm"
          shadow="sm"
          href="https://drive.google.com/file/d/1QkF7VNpAJoWCLBu6mc4F7oJJtGfNHgT0/view?usp=sharing"
          target="_blank"
          class="w-fit"
        >
          <DownloadIcon class="mr-2 size-4 stroke-[2.5]" />
          Download Resume (PDF)
        </NeobrutalismButton>
      </div>

      <section id="summary" class="scroll-mt-20">
        <h2 class="font-transducer-extended text-xl font-bold">Summary:</h2>
        <div class="mb-5"></div>
        <div>
          <p class="text-sm md:leading-relaxed">
            Results-oriented Software Engineer, proficient in Frontend Development, and well-versed
            in DevOps practices. Adept at crafting high-performance, user-centric applications with
            a keen eye for detail. Demonstrated success in optimizing software delivery pipelines,
            implementing scalable solutions, and fostering cross-functional collaboration. Proactive
            problem-solver with a passion for staying abreast of emerging technologies. Seeking a
            challenging role to leverage technical expertise and contribute to innovative projects
            in a dynamic environment.
          </p>
        </div>
        <div class="mb-8"></div>
      </section>

      <section id="experience" class="scroll-mt-20">
        <h2 class="font-transducer-extended text-xl font-bold">Experience:</h2>
        <div class="mb-5"></div>
        <div>
          <Timeline data={experiencesTimeline} />
        </div>
        <div class="mb-8"></div>
      </section>

      <section id="education" class="scroll-mt-20">
        <h2 class="font-transducer-extended text-xl font-bold">Education:</h2>
        <div class="mb-5"></div>
        <div>
          <Timeline data={educationsTimeline} />
        </div>
        <div class="mb-8"></div>
      </section>

      <section id="technical-skills" class="scroll-mt-20">
        <h2 class="font-transducer-extended text-xl font-bold">Technical Skills:</h2>
        <div class="mb-5"></div>
        <div>
          <Skills data={technicalSkills} />
        </div>
        <div class="mb-8"></div>
      </section>

      <section id="other-skills" class="scroll-mt-20">
        <h2 class="font-transducer-extended text-xl font-bold">Other Skills:</h2>
        <div class="mb-5"></div>
        <div>
          <Skills data={otherSkills} />
        </div>
        <div class="mb-8"></div>
      </section>

      <section id="knowledges" class="scroll-mt-20">
        <h2 class="font-transducer-extended text-xl font-bold">Knowledges:</h2>
        <div class="mb-5"></div>
        <div>
          <ul class="flex flex-wrap gap-2">
            {#each knowledge as item (item)}
              <li class="contents">
                <NeobrutalismBadge class="rounded" shadow="sm">
                  {item}
                </NeobrutalismBadge>
              </li>
            {/each}
          </ul>
        </div>
        <div class="mb-10"></div>
      </section>

      <section id="certifications" class="scroll-mt-20">
        <h2 class="font-transducer-extended text-xl font-bold">Certifications:</h2>
        <div class="mb-5"></div>
        <div>
          <Certificates data={certificates} />
        </div>
      </section>
    </div>

    <!-- spacer -->
    <div class="hidden h-0 w-12 lg:block xl:w-20"></div>

    <!-- Table of Contents Sidebar -->
    <div class="hidden lg:block lg:w-84 lg:shrink-0 xl:w-96">
      {#if isLarge.current}
        <!-- 
          The value '2' is added for the header border.
          The value '32' is added for padding (could be top or bottom padding).
        -->
        <TableOfContents
          class="sticky overflow-y-auto"
          style={`
            top: ${HEADER_HEIGHT + 2 + 32}px;
            max-height: calc(100vh - ${HEADER_HEIGHT + 2 + 32 + 32}px);
          `}
          sections={tocSections}
        />
      {/if}
    </div>
  </div>
</main>

// packages/resume-pdf/src/Resume.tsx
import "./Resume.css";
import { certificates, education, experiences, knowledge, personalInfo } from "@nurliman.dev/data";
import { clsx } from "clsx";
import { Github, Globe, Linkedin, Mail, MapPin, Phone } from "lucide-react";
import type { ComponentProps } from "react";
import snarkdown from "snarkdown";

export default function Resume({ className, ...props }: ComponentProps<"div"> = {}) {
  return (
    <div className={clsx("bg-white font-serif leading-relaxed text-black", className)} {...props}>
      {/* Header */}
      <div className="mb-6 text-center">
        <h1 className="mb-3 text-3xl font-bold text-gray-900">{personalInfo.name}</h1>
        <div className="mb-3 text-lg font-medium text-gray-700">
          Full-Stack Developer & DevOps Engineer
        </div>
        <div className="flex flex-wrap justify-center gap-4 text-sm text-gray-600">
          <a href={`mailto:${personalInfo.email}`} className="flex items-center gap-1">
            <Mail className="size-4" />
            {personalInfo.email}
          </a>
          <a
            href={personalInfo.whatsappLink}
            className="flex items-center gap-1"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Phone className="size-4" />
            {personalInfo.phoneFormatted}
          </a>
          <div className="flex items-center gap-1">
            <MapPin className="size-4" />
            {personalInfo.residence}
          </div>
          <a
            href={personalInfo.websiteLink}
            className="flex items-center gap-1"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Globe className="size-4" />
            nurliman.dev
          </a>
          <a
            href={personalInfo.githubLink}
            className="flex items-center gap-1"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Github className="size-4" />
            github.com/nurliman
          </a>
          <a
            href={personalInfo.linkedinLink}
            className="flex items-center gap-1"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Linkedin className="size-4" />
            linkedin.com/in/nurliman
          </a>
        </div>
      </div>

      {/* Summary */}
      <section className="mb-6">
        <h2 className="mb-3 border-b border-gray-200 pb-1 text-lg font-semibold text-gray-900">
          SUMMARY
        </h2>
        <p className="leading-relaxed text-gray-700">
          Results-driven software engineer with 5+ years of experience building scalable web
          applications. Expert in JavaScript/TypeScript, cloud infrastructure, and modern
          development practices. Specialize in creating high-performance, user-centric applications
          with meticulous attention to detail. Proven track record of optimizing software delivery
          pipelines, implementing scalable solutions, and fostering cross-functional collaboration.
          Proactive problem-solver who stays current with emerging technologies and seeks
          challenging opportunities to leverage technical expertise in innovative projects.
        </p>
      </section>

      {/* TODO: Replace hardcoded skills with dynamic data */}
      {/* Skills (Hardcoded) */}
      <section className="mb-6">
        <h2 className="mb-3 border-b border-gray-200 pb-1 text-lg font-semibold text-gray-900">
          SKILLS
        </h2>
        <div className="space-y-4">
          {/* Core Programming & Development */}
          <div>
            <h3 className="mb-1 font-medium text-gray-800">Programming Languages & Frameworks</h3>
            <div className="text-sm leading-relaxed text-gray-600">
              {formatSkills(["JavaScript/TypeScript", "Node.js", "React", "Next.js", "Go", "Rust"])}
            </div>
          </div>

          {/* DevOps & Infrastructure */}
          <div>
            <h3 className="mb-1 font-medium text-gray-800">DevOps & Infrastructure</h3>
            <div className="text-sm leading-relaxed text-gray-600">
              {formatSkills([
                "Docker",
                "Kubernetes",
                "Jenkins",
                "GitHub Actions",
                "Google Cloud Platform",
                "Linux",
                "Nginx",
              ])}
            </div>
          </div>

          {/* Frontend Technologies */}
          <div>
            <h3 className="mb-1 font-medium text-gray-800">Frontend Technologies</h3>
            <div className="text-sm leading-relaxed text-gray-600">
              {formatSkills([
                "React",
                "Redux",
                "TailwindCSS",
                "styled-components",
                "SCSS",
                "Storybook",
                "Svelte",
                "Solid.js",
                "Astro",
              ])}
            </div>
          </div>

          {/* Mobile & Desktop */}
          <div>
            <h3 className="mb-1 font-medium text-gray-800">Mobile & Desktop Development</h3>
            <div className="text-sm leading-relaxed text-gray-600">
              {formatSkills(["React Native", "Expo", "Electron"])}
            </div>
          </div>

          {/* APIs & Databases */}
          <div>
            <h3 className="mb-1 font-medium text-gray-800">APIs & Databases</h3>
            <div className="text-sm leading-relaxed text-gray-600">
              {formatSkills([
                "REST API",
                "OpenAPI",
                "GraphQL",
                "PostgreSQL",
                "MySQL",
                "SQLite",
                "Elasticsearch",
                "Meilisearch",
              ])}
            </div>
          </div>

          {/* Development Tools & Design */}
          <div>
            <h3 className="mb-1 font-medium text-gray-800">Development Tools & Design</h3>
            <div className="text-sm leading-relaxed text-gray-600">
              {formatSkills([
                "Git/GitHub",
                "Jest",
                "Vite",
                "Vitest",
                "Playwright",
                "Sentry",
                "Turborepo",
                "Figma",
                "Adobe Illustrator",
              ])}
            </div>
          </div>
        </div>
      </section>

      {/* Professional Experience */}
      {experiences?.length ? (
        <section className="mb-6">
          <h2 className="mb-3 border-b border-gray-200 pb-1 text-lg font-semibold text-gray-900">
            PROFESSIONAL EXPERIENCE
          </h2>
          <div className="space-y-6">
            {experiences.map((exp, index) => (
              <div key={index}>
                <div className="mb-2 flex items-start justify-between">
                  <div>
                    <h3 className="font-semibold text-gray-900">{exp.title}</h3>
                    <p className="text-gray-700">{exp.company}</p>
                  </div>
                  <p className="text-sm font-medium text-gray-600">{exp.period}</p>
                </div>
                <div className="markdown leading-relaxed text-gray-700">
                  {renderMarkdown(exp.description)}
                </div>
              </div>
            ))}
          </div>
        </section>
      ) : null}

      {/* Education */}
      {education?.length ? (
        <section className="mb-6">
          <h2 className="mb-3 border-b border-gray-200 pb-1 text-lg font-semibold text-gray-900">
            EDUCATION
          </h2>
          <div className="space-y-4">
            {education.map((edu, index) => (
              <div key={index}>
                <div className="mb-2 flex items-start justify-between">
                  <div>
                    <h3 className="font-semibold text-gray-900">{edu.field}</h3>
                    <p className="text-gray-700">{edu.school}</p>
                  </div>
                  <p className="text-sm font-medium text-gray-600">{edu.period}</p>
                </div>
                <div className="markdown leading-relaxed text-gray-700">
                  {renderMarkdown(edu.description)}
                </div>
              </div>
            ))}
          </div>
        </section>
      ) : null}

      {/* Knowledge Areas */}
      {knowledge?.length ? (
        <section className="mb-6">
          <h2 className="mb-3 border-b border-gray-200 pb-1 text-lg font-semibold text-gray-900">
            KNOWLEDGE AREAS
          </h2>
          <p className="leading-relaxed text-gray-700">{knowledge.join(" • ")}</p>
        </section>
      ) : null}

      {/* Certifications */}
      {certificates?.length ? (
        <section className="mb-6">
          <h2 className="mb-3 border-b border-gray-200 pb-1 text-lg font-semibold text-gray-900">
            CERTIFICATIONS
          </h2>
          <div className="space-y-4">
            {certificates.map((cert, index) => (
              <div key={index} className="flex items-start justify-between">
                <div>
                  <span className="font-medium text-gray-900">{cert.name}</span>
                  <span className="text-gray-600"> • {cert.organization.name}</span>
                  <div className="text-sm text-gray-500">Credential ID: {cert.credential.id}</div>
                </div>
                <span className="text-sm text-gray-600">{cert.date}</span>
              </div>
            ))}
          </div>
        </section>
      ) : null}
    </div>
  );
}

function formatSkills(skills: string[]) {
  return skills.join(" • ");
}

/**
 * Renders markdown text and replaces <br/> tags with stylable React elements.
 *
 * Why we do this:
 * - Standard <br/> tags cannot be styled for height/spacing
 * - We need consistent, controllable line breaks for PDF generation
 * - This approach converts HTML line breaks into React divs with custom styling
 *
 * @param text - Markdown text that may contain line breaks
 * @returns Array of React elements with stylable line breaks
 */
function renderMarkdown(text: string) {
  const html = snarkdown(text);

  // Replace <br> and <br/> tags with unique placeholder markers
  // This allows us to safely split the HTML without breaking other tags
  const processed = html.replace(/<br\s*\/?>/gi, "|||LINEBREAK|||");

  // Split by placeholder to separate HTML content from line break positions
  const parts = processed.split("|||LINEBREAK|||");

  return parts.map((part, index) => (
    <span key={index}>
      {/* Insert stylable line break div instead of <br/> tag */}
      {index > 0 ? <div className="block h-2 w-full" /> : null}
      <span dangerouslySetInnerHTML={{ __html: part }} />
    </span>
  ));
}
