// apps/portfolio/src/components/TheFooter.tsx
import { socials } from "@/data/socials";
import { clsx } from "clsx";
import { For, Show, createSignal, onMount } from "solid-js";

export default function TheFooter() {
  const [currentYear, setCurrentYear] = createSignal(new Date().getFullYear());

  onMount(() => {
    setCurrentYear(new Date().getFullYear());
  });

  return (
    <footer class="bg-zinc-900 px-4 pt-10 pb-28 text-zinc-400 sm:px-6 lg:px-8">
      <div
        class={clsx([
          "flex flex-col-reverse items-center justify-between md:flex-row",
          "container mx-auto",
          "text-sm max-md:text-center",
        ])}
      >
        <div>© {currentYear()} All rights reserved.</div>
        <div class="h-6 md:h-0" />
        <div class="flex-center flex-row">
          <For each={socials}>
            {(social, index) => (
              <>
                <a
                  href={social.link}
                  class="underline underline-offset-2 hover:text-zinc-100"
                  target="_blank"
                  rel="noreferrer"
                >
                  {social.name}
                </a>
                <Show when={index() < socials.length - 1}>
                  <span>&nbsp;|&nbsp;</span>
                </Show>
              </>
            )}
          </For>
        </div>
      </div>
    </footer>
  );
}

// apps/portfolio/src/lib/components/TheFooter.svelte
<script lang="ts">
  import { socials } from "$lib/data/socials";
  import { cn } from "$lib/utils/shadcn";
  import { onMount } from "svelte";

  let currentYear = $state(new Date().getFullYear());

  onMount(() => {
    currentYear = new Date().getFullYear();
  });
</script>

<footer class="bg-zinc-900 pt-10 pb-28 text-zinc-400">
  <div
    class={cn([
      "flex flex-col-reverse items-center justify-between md:flex-row",
      "container mx-auto",
      "text-sm max-md:text-center",
    ])}
  >
    <div>© {currentYear} All rights reserved.</div>
    <div class="h-6 md:h-0"></div>
    <div class="flex-center flex-row">
      {#each socials as social, index}
        <a
          href={social.link}
          class="underline underline-offset-2 hover:text-zinc-100"
          target="_blank"
          rel="noreferrer"
        >
          {social.name}
        </a>
        {#if index < socials.length - 1}
          <span>&nbsp;|&nbsp;</span>
        {/if}
      {/each}
    </div>
  </div>
</footer>
