// apps/portfolio/src/components/TheHamburgerButton.tsx
import { Button } from "@/components/ui/button";
import { clsx } from "clsx";
import type { Accessor, ComponentProps } from "solid-js";
import { splitProps } from "solid-js";

export type TheHamburgerButtonProps = {
  isSidebarOpen: Accessor<boolean>;
} & ComponentProps<typeof Button>;

export default function TheHamburgerButton(props: TheHamburgerButtonProps) {
  const [localProps, restProps] = splitProps(props, [
    "children",
    "class",
    "classList",
    "isSidebarOpen",
  ]);

  return (
    <Button
      {...restProps}
      variant="ghost"
      size="sm"
      class={clsx(
        "!h-auto !min-h-[3rem] !w-12 relative flex-center",
        "!rounded-none border-r",
        localProps.class,
        localProps.classList,
      )}
    >
      <img
        src="/assets/menu-burger.svg"
        alt="Menu"
        height="28px"
        width="28px"
        loading="lazy"
        class={clsx(
          "absolute-center transition-opacity dark:hidden",
          localProps.isSidebarOpen() ? "opacity-0" : "opacity-100",
        )}
      />
      <img
        src="/assets/menu-close.svg"
        alt="Close"
        height="28px"
        width="28px"
        loading="lazy"
        class={clsx(
          "absolute-center transition-opacity dark:hidden",
          localProps.isSidebarOpen() ? "opacity-100" : "opacity-0",
        )}
      />
      <img
        src="/assets/menu-burger-dark.svg"
        alt="Menu"
        height="28px"
        width="28px"
        loading="lazy"
        class={clsx(
          "absolute-center hidden transition-opacity dark:block",
          localProps.isSidebarOpen() ? "opacity-0" : "opacity-100",
        )}
      />
      <img
        src="/assets/menu-close-dark.svg"
        alt="Close"
        height="28px"
        width="28px"
        loading="lazy"
        class={clsx(
          "absolute-center hidden transition-opacity dark:block",
          localProps.isSidebarOpen() ? "opacity-100" : "opacity-0",
        )}
      />
    </Button>
  );
}

// apps/portfolio/src/lib/components/TheHamburgerButton.svelte
<script lang="ts">
  import { Button, type ButtonProps } from "$lib/components/ui/button";
  import { cn } from "$lib/utils/shadcn";

  type Props = {
    isSidebarOpen: boolean;
  } & ButtonProps;

  let { isSidebarOpen, class: className, ...restProps }: Props = $props();
</script>

<Button
  {...restProps}
  variant="ghost"
  size="sm"
  class={cn(
    "flex-center relative !h-auto !min-h-[3rem] !w-12",
    "!rounded-none border-r",
    "cursor-pointer",
    className,
  )}
>
  <img
    src="/assets/menu-burger.svg"
    alt="Menu"
    height="28"
    width="28"
    loading="lazy"
    class={cn(
      "absolute-center transition-opacity dark:hidden",
      isSidebarOpen ? "opacity-0" : "opacity-100",
    )}
  />
  <img
    src="/assets/menu-close.svg"
    alt="Close"
    height="28"
    width="28"
    loading="lazy"
    class={cn(
      "absolute-center transition-opacity dark:hidden",
      isSidebarOpen ? "opacity-100" : "opacity-0",
    )}
  />
  <img
    src="/assets/menu-burger-dark.svg"
    alt="Menu"
    height="28"
    width="28"
    loading="lazy"
    class={cn(
      "absolute-center hidden transition-opacity dark:block",
      isSidebarOpen ? "opacity-0" : "opacity-100",
    )}
  />
  <img
    src="/assets/menu-close-dark.svg"
    alt="Close"
    height="28"
    width="28"
    loading="lazy"
    class={cn(
      "absolute-center hidden transition-opacity dark:block",
      isSidebarOpen ? "opacity-100" : "opacity-0",
    )}
  />
</Button>
