// apps/portfolio/src/lib/components/TheHeader.svelte
<script lang="ts">
  import { page } from "$app/state";
  import TheHamburgerButton from "$lib/components/TheHamburgerButton.svelte";
  import TheSidebar from "$lib/components/TheSidebar.svelte";
  import TheThemeSwitcher from "$lib/components/TheThemeSwitcher.svelte";
  import { Button } from "$lib/components/ui/button";
  import { sections } from "$lib/data/sections";
  import { isActivePath } from "$lib/utils/isActivePath";

  let headerHeight = 50;
  let sidebarOpened = $state(false);

  const changeSidebarOpened = (newState?: boolean) => {
    newState = newState ?? !sidebarOpened;
    sidebarOpened = newState;
  };

  const closeSidebar = () => {
    changeSidebarOpened(false);
  };
</script>

<header
  bind:offsetHeight={headerHeight}
  class={[
    "fixed top-0 z-30 w-full overflow-hidden",
    "border-b-2 border-black bg-white/60 transition-colors",
    "dark:border-zinc-800 dark:bg-[#1d1d1f]/40 dark:text-white",
  ]}
  style:backdrop-filter="blur(20px) saturate(180%)"
  style:transition-timing-function="cubic-bezier(.28,.11,.32,1)"
  style:transition-duration=".5s"
>
  <div class="mx-auto flex items-center justify-between gap-x-4 md:container md:h-[52px]">
    <TheHamburgerButton
      class="md:hidden"
      isSidebarOpen={sidebarOpened}
      onclick={() => changeSidebarOpened()}
    />

    <div class="max-md:absolute-center flex-center md:py-2">
      <Button
        href="/"
        variant="link"
        class="font-racing-sans !p-0 text-[1.75rem] md:text-3xl"
        onclick={() => closeSidebar()}
      >
        nurliman.
      </Button>
    </div>

    <div class="hidden h-7 w-px bg-zinc-600 md:flex"></div>

    <nav class="hidden md:contents">
      <ul class="flex flex-1 flex-row items-center">
        {#each sections as section (section.id)}
          <li class="contents">
            <Button
              href={section.link}
              size="sm"
              variant="ghost"
              class={[
                "h-fit !rounded-full !px-3 !py-1.5 !text-xs font-normal uppercase",
                isActivePath(section.link, page.url.pathname) && "menu-link-active",
              ]}
              onclick={() => closeSidebar()}
            >
              {section.name}
            </Button>
          </li>
        {/each}
      </ul>
    </nav>

    <TheThemeSwitcher class="relative max-md:right-2" />
  </div>
</header>

<TheSidebar {headerHeight} isOpen={sidebarOpened} onChange={changeSidebarOpened} />

// apps/portfolio/src/components/TheHeader.tsx
import TheHamburgerButton from "@/components/TheHamburgerButton";
import TheSidebar from "@/components/TheSidebar";
import TheThemeSwithcerButton from "@/components/TheThemeSwithcerButton";
import { Button } from "@/components/ui/button";
import { sections } from "@/data/sections";
import { isActivePath } from "@/utils/isActivePath";
import { createMediaQuery } from "@solid-primitives/media";
import { clsx } from "clsx";
import { For, Show, createSignal, onCleanup, onMount } from "solid-js";

export type TheHeaderProps = {
  currentPath: string;
};

export default function TheHeader(props: TheHeaderProps) {
  const isMobile = createMediaQuery("(max-width: 767px)", false);
  const [currentPath, setCurrentPath] = createSignal(props.currentPath);
  const [sidebarOpened, setSidebarOpened] = createSignal(false);

  const changeMenuOpened = (isOpen?: boolean) => {
    setSidebarOpened((sidebarOpened) => {
      const newState = isOpen ?? !sidebarOpened;
      return newState;
    });
  };

  const closeMenu = () => {
    sidebarOpened() && changeMenuOpened(false);
  };

  onMount(() => {
    // biome-ignore lint/suspicious/noExplicitAny: cant find type for astro:after-swap event
    const setPath = (evt?: any) => {
      const pathname = evt?.target?.location?.pathname || window.location.pathname;
      setCurrentPath(pathname);
    };

    setPath();

    document.addEventListener("astro:after-swap", setPath);

    onCleanup(() => {
      document.removeEventListener("astro:after-swap", setPath);
    });
  });

  return (
    <>
      <header
        class={clsx(
          "fixed top-0 z-30 w-full overflow-hidden border-b-2",
          "bg-white/60 transition-colors dark:bg-[#1d1d1f]/40 dark:text-white",
        )}
        style={{
          "backdrop-filter": "blur(20px) saturate(180%)",
          "transition-timing-function": "cubic-bezier(.28,.11,.32,1)",
          "transition-duration": ".5s",
        }}
      >
        <div
          class={clsx(
            "flex items-center justify-between gap-x-4",
            "mx-auto md:container md:h-[52px]",
          )}
        >
          <TheHamburgerButton
            class="md:hidden"
            isSidebarOpen={sidebarOpened}
            onClick={() => changeMenuOpened()}
          />

          <div class="max-md:absolute-center flex-center md:py-2">
            <Button
              as="a"
              href="/"
              variant="link"
              class="!p-0 font-racing-sans text-[1.75rem] md:text-3xl"
              onClick={() => closeMenu()}
            >
              nurliman.
            </Button>
          </div>

          <div class="hidden h-7 w-px bg-zinc-600 md:flex" />

          <nav class="hidden md:contents">
            <ul class="flex flex-1 flex-row items-center">
              <For each={sections}>
                {(section) => (
                  <li class="contents">
                    <Button
                      as="a"
                      href={section.link}
                      size="sm"
                      variant="ghost"
                      class={clsx(
                        "!rounded-full !px-3 !py-1.5 !text-xs h-fit font-normal uppercase",
                        isActivePath(section.link, currentPath()) && "menu-link-active",
                      )}
                      onClick={() => closeMenu()}
                    >
                      {section.name}
                    </Button>
                  </li>
                )}
              </For>
            </ul>
          </nav>

          <TheThemeSwithcerButton class="relative max-md:right-2" />
        </div>
      </header>

      <Show when={isMobile()}>
        <TheSidebar
          isOpen={sidebarOpened}
          currentPath={currentPath}
          headerHeight={50}
          onChange={(isOpen) => changeMenuOpened(isOpen)}
        />
      </Show>
    </>
  );
}
