// apps/portfolio-next/src/components/TheHamburgerButton.vue
<script setup lang="ts">
import TheButton from "~/components/TheButton.vue";

const { isSidebarOpen } = defineProps<{
  isSidebarOpen: boolean;
}>();
const emit = defineEmits<{
  (e: "click"): void;
}>();
</script>

<template>
  <TheButton
    :class="['flex-center relative', 'h-auto min-h-[3rem] w-12 border-r']"
    @click="emit('click')"
  >
    <img
      src="/assets/menu-burger.svg"
      alt="Menu"
      height="28px"
      width="28px"
      loading="lazy"
      class="absolute-center transition-opacity dark:hidden"
      :class="{ 'opacity-0': isSidebarOpen, 'opacity-100': !isSidebarOpen }"
    />
    <img
      src="/assets/menu-close.svg"
      alt="Close"
      height="28px"
      width="28px"
      loading="lazy"
      class="absolute-center transition-opacity dark:hidden"
      :class="{ 'opacity-0': !isSidebarOpen, 'opacity-100': isSidebarOpen }"
    />
    <img
      src="/assets/menu-burger-dark.svg"
      alt="Menu"
      height="28px"
      width="28px"
      loading="lazy"
      class="absolute-center hidden transition-opacity dark:block"
      :class="{ 'opacity-0': isSidebarOpen, 'opacity-100': !isSidebarOpen }"
    />
    <img
      src="/assets/menu-close-dark.svg"
      alt="Close"
      height="28px"
      width="28px"
      loading="lazy"
      class="absolute-center hidden transition-opacity dark:block"
      :class="{ 'opacity-0': !isSidebarOpen, 'opacity-100': isSidebarOpen }"
    />
  </TheButton>
</template>

// apps/portfolio/src/components/TheHamburgerButton.tsx
import TheButton from "@/components/TheButton";
import { clsx } from "clsx";
import type { Accessor, ComponentProps } from "solid-js";
import { splitProps } from "solid-js";

export type TheHamburgerButtonProps = {
  isSidebarOpen: Accessor<boolean>;
} & ComponentProps<typeof TheButton<"button">>;

export default function TheHamburgerButton(props: TheHamburgerButtonProps) {
  const [localProps, restProps] = splitProps(props, [
    "children",
    "class",
    "classList",
    "isSidebarOpen",
  ]);

  return (
    <TheButton
      {...restProps}
      class={clsx(
        "flex-center relative h-auto min-h-[3rem] w-12 border-r",
        localProps.class,
        localProps.classList,
      )}
    >
      <img
        src="/assets/menu-burger.svg"
        alt="Menu"
        height="28px"
        width="28px"
        loading="lazy"
        class={clsx(
          "absolute-center transition-opacity dark:hidden",
          localProps.isSidebarOpen() ? "opacity-0" : "opacity-100",
        )}
      />
      <img
        src="/assets/menu-close.svg"
        alt="Close"
        height="28px"
        width="28px"
        loading="lazy"
        class={clsx(
          "absolute-center transition-opacity dark:hidden",
          localProps.isSidebarOpen() ? "opacity-100" : "opacity-0",
        )}
      />
      <img
        src="/assets/menu-burger-dark.svg"
        alt="Menu"
        height="28px"
        width="28px"
        loading="lazy"
        class={clsx(
          "absolute-center hidden transition-opacity dark:block",
          localProps.isSidebarOpen() ? "opacity-0" : "opacity-100",
        )}
      />
      <img
        src="/assets/menu-close-dark.svg"
        alt="Close"
        height="28px"
        width="28px"
        loading="lazy"
        class={clsx(
          "absolute-center hidden transition-opacity dark:block",
          localProps.isSidebarOpen() ? "opacity-100" : "opacity-0",
        )}
      />
    </TheButton>
  );
}
