// apps/portfolio/src/lib/components/TheSidebar.svelte
<script lang="ts">
  import { page } from "$app/state";
  import { Button } from "$lib/components/ui/button";
  import { sections } from "$lib/data/sections";
  import { isActivePath } from "$lib/utils/isActivePath";

  type Props = {
    isOpen: boolean;
    headerHeight: number;
    onChange?: (isOpen: boolean) => void;
  };

  let { isOpen, headerHeight, onChange }: Props = $props();
</script>

<!-- Overlay button -->
<button
  type="button"
  class={[
    "fixed inset-0 z-10 w-screen bg-black",
    "transition-opacity duration-300 ease-out",
    "md:hidden",
    isOpen ? "pointer-events-auto opacity-50" : "pointer-events-none opacity-0",
  ]}
  style:height="calc(100% - {headerHeight}px)"
  style:top="{headerHeight}px"
  style:transform="translateZ(0)"
  onclick={() => onChange?.(false)}
  data-aria-hidden="true"
  aria-hidden="true"
  aria-label="Sidebar overlay"
>
</button>

<!-- Sidebar -->
<div
  class={[
    "fixed z-40 flex w-screen flex-col will-change-transform md:hidden",
    "bg-background text-foreground border-r border-black dark:border-zinc-800",
    "transition-all duration-300 ease-out sm:max-w-xs",
  ]}
  style:height="calc(100vh - {headerHeight}px)"
  style:top="{headerHeight}px"
  style:transform="translate3d({isOpen ? '0' : '-100%'}, 0, 0)"
>
  <nav class="contents">
    <ul class="flex flex-col text-xs uppercase">
      {#each sections as section (section.id)}
        <li class="contents">
          <Button
            href={section.link}
            variant="ghost"
            class={[
              "cursor-pointer !justify-start !rounded-none",
              "border-b border-black dark:border-zinc-800",
              "!px-8 !py-5 text-xs font-normal",
              isActivePath(section.link, page.url.pathname) && "menu-link-active",
            ]}
            onclick={() => onChange?.(false)}
          >
            {section.name}
          </Button>
        </li>
      {/each}
    </ul>
  </nav>
</div>

// apps/portfolio/src/components/TheSidebar.tsx
import { Button } from "@/components/ui/button";
import { sections } from "@/data/sections";
import { socials } from "@/data/socials";
import { isActivePath } from "@/utils/isActivePath";
import { clsx } from "clsx";
import { type Accessor, For } from "solid-js";

export type TheSidebarProps = {
  isOpen: Accessor<boolean>;
  currentPath: Accessor<string>;
  headerHeight: number;
  onChange?: (isOpen: boolean) => void;
};

export default function TheSidebar(props: TheSidebarProps) {
  return (
    <>
      <button
        type="button"
        class={clsx(
          "fixed inset-0 z-10 w-screen bg-black transition-opacity duration-300 md:hidden",
          props.isOpen() ? "pointer-events-auto opacity-50" : "pointer-events-none opacity-0",
        )}
        style={{
          height: `calc(100% - ${props.headerHeight}px)`,
          top: `${props.headerHeight}px`,
          transform: "translateZ(0)",
        }}
        onClick={() => props.onChange?.(false)}
        data-aria-hidden
        aria-hidden
        aria-label="Sidebar overlay"
      />

      <div
        class={clsx(
          "fixed z-40 flex flex-col will-change-transform md:hidden",
          "w-screen border-r bg-white sm:max-w-xs dark:bg-black",
        )}
        style={{
          height: `calc(100vh - ${props.headerHeight}px)`,
          top: `${props.headerHeight}px`,
          transform: `translate3d(${props.isOpen() ? "0" : "-100%"},0,0)`,
          transition: "background-color .1s ease-in-out,transform .25s cubic-bezier(.55,0,1,.45)",
        }}
      >
        <nav class="contents">
          <ul class="flex flex-col text-xs uppercase">
            <For each={sections}>
              {(section) => (
                <li class="contents">
                  <Button
                    as="a"
                    href={section.link}
                    variant="ghost"
                    class={clsx(
                      "!rounded-none !px-8 !py-5 !justify-start border-b",
                      "font-normal text-xs",
                      isActivePath(section.link, props.currentPath()) && "menu-link-active",
                    )}
                    onClick={() => props.onChange?.(false)}
                  >
                    {section.name}
                  </Button>
                </li>
              )}
            </For>
          </ul>
        </nav>
        <div class="h-px w-px flex-1" />
        <div class="flex border-t bg-white px-8 py-5 transition-colors dark:bg-black">
          <ul class="flex flex-row space-x-3.5">
            <For each={socials}>
              {(social) => (
                <li class="flex">
                  <Button
                    as="a"
                    href={social.link}
                    target="_blank"
                    size="icon"
                    variant="outline"
                    class="border-black/70 dark:border-border"
                  >
                    <img
                      src={social.iconUrl}
                      alt={social.name}
                      loading="lazy"
                      class="h-[18px] w-[18px] dark:hidden"
                    />
                    <img
                      src={social.iconDarkUrl}
                      alt={social.name}
                      loading="lazy"
                      class="hidden h-[18px] w-[18px] dark:block"
                    />
                  </Button>
                </li>
              )}
            </For>
          </ul>
        </div>
      </div>
    </>
  );
}
